name: LogiDelivery
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3        # For state management
  firebase_core: ^4.1.1   # Firebase setup for auth, firestore, etc.
  firebase_auth: ^6.1.0    # Firebase Authentication
  cloud_firestore: ^6.0.2  # Firestore database
  dio: ^5.1.0             # Networking and API calls
  intl: ^0.20.2           # Internationalization and date formatting
  get: ^4.6.5             # Route management, can use GetX for state too
  flutter_local_notifications: ^19.2.1  # Push notifications
  firebase_storage: ^13.0.2
  firebase_app_check: ^0.4.1 # Add the latest version
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.0.0
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.4
  flutter_spinkit: ^5.2.0
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  intl_phone_field: ^3.2.0
  geolocator_android: ^5.0.2
  http: ^1.2.1
  location: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/login_bg.jpg
    - assets/images/small.jpg
    - assets/images/login_bg.png
    - assets/images/medium.jpg
    - assets/images/large.jpg
    - assets/images/bike.png
    - assets/images/car.png
    - assets/images/tricycle.png

 
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
